language: node_js
node_js:
- 9
branches:
  only:
  - master
install:
- yarn
before_script:
- yarn run build
- yarn run npm-patch
- rm .npmrc
script:
- yarn run build:example
after_success: 
deploy:
  skip_cleanup: true
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: "$HEROKU_KEY"
  app: "$HEROKU_APP"
  run: