export const SET_VISIBLE = 'SET_VISIBLE'
export const SET_UPLOADS = 'SET_UPLOADS'
export const SET_DRAG = 'SET_DRAG'
export const SET_WINDOW_CLICK = 'SET_WINDOW_CLICK'
export const SET_DIMENSIONS = 'SET_DIMENSIONS'
export const SET_MODAL = 'SET_MODAL'
export const SET_VIEW = 'SET_VIEW'
